// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ItemModal: typeof import('./src/components/ItemModal.vue')['default']
    ItemsListItem: typeof import('./src/components/ItemsListItem.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
  }
}

export { }
